### PR TITLE
Modified the Now Playing screen to fullscreen which means removed  th…

### PR DESCRIPTION
**Pull request by jenuprasad**
…e toolabr and in now playing screen  made transprent view with back button

### CODE REVIEW

**Comment by naman14** [comment]
Hey, can you post screenshots describing the changes?

**Comment by Kasijjuf** [comment]
Don't bump the minSDK from 16 to 21 just for this. This change is not worth the loss of device support.

**Comment by jenuprasad** [comment]
@naman14  Here i made the now playing screen to fullscreen http://imgur.com/QmiA8Sc

**Comment by naman14** [comment]
@jenuprasad  There doesn't seems to be any visual difference and you removed the Toolbar altogether which removes the search icon from now playing.
Plus, your pull request is vague and as @Kasijjuf  mentioned why will you even bump the min sdk version? You have done  more random changes than you have mentioned in your message.
Unfortunately, I will have to close this pull requests.

**Pull request closed without merging**
