### PR TITLE
fix bugs

### PR DESCRIPTION
**Pull request by dkonurov**
change build tools and add picasso, butter knife, add translate and fix bugs with change orientation in playlistdetailactivity

### CODE REVIEW

**Comment by dkonurov** [comment]
I'm gradually add butter knife in all activity and fragmend, and universal loader manager requires more row code, picasso compact, if those library don't need i can delete it :-)

**Comment by Kasijjuf** [comment]
Separate out your changes into different pull requests. Don't lump together bug fixes with introducing completely new libraries.

**Comment by Kasijjuf** [comment]
Also rebase your changes onto the head of the master branch. You are working off of an old version.

**Comment by dkonurov** [comment]
thank you. I understood my mistakes. today changes try changes commit. may i use new library? or not?

**Comment by Kasijjuf** [comment]
If you want to use a new library, demonstrate with a commit how that library simplifies the codebase and makes code maintenance easier. Make the commit focused; this commit should have been four or five separate commits:
* Update build tools
* Add translation
* Fix orientation bug
* Add libraries (possibly one commit per library)

**Pull request closed without merging**
