### PR TITLE
Fix wrong track number and song duration in style3

### PR DESCRIPTION
**Pull request by angiecho**

### CODE REVIEW

**Comment by Tangleworm** [comment]
This is for #29! We made the song length and duration visible on timber 3.

**Comment by Tangleworm** [comment]
Fix for #55 also added; we were unable to repro #56.

**Comment by JustinLy** [comment]
For issue #55 the current fix will only work for albums of less than 1000 tracks. Details below:

 I found the source of the bug to be in AlbumSongLoader.java in the getSongsForAlbum() method. On line 44:               int trackNumber = cursor.getInt(5);
For random albums (single disk and multi disk) some or all tracks will be 1000 or 2000 greater than its real track number. For example, a song with track number 1, may end up as 1001 or 2001. I fixed the issue by adding a loop to check for track numbers >= 1000 and decreasing by 1000 until this was no longer the case. However, this will prove problematic for albums with >= 1000 tracks as the 1000th track will have 0 as its track number and so on.

**Comment by naman14** [comment]
@Tangleworm @angiecho Great!
@JustinLy Cool! I think this fixes the problem in most of the general cases.

**Pull request merged**
