### PR TITLE
Real dark and Real Black

### PR DESCRIPTION
**Pull request by CallMeAldy**
I think this would be a better approach since this is what we usually
see. I older dark and black looks odd and spoils the beauty of the music
player

### CODE REVIEW

**Comment by naman14** [comment]
I think the current dark looks good and the black should be pure black as is currently. I will take a poll on the G+ community whether the current dark themes needs to be changed and if then to which colors.

**Comment by naman14** [comment]
Dark theme colors will be changed but shouldn't black be purely black? Why change black theme colors?

**Comment by CallMeAldy** [comment]
@naman14 Maybe because the selected black colors totally take away the material look and it feels like going from Material to Holo just with a theme change. Logically, 90% of the area covered on the screen is totally black so having the actionbar and statusbar with a different color does not really matter IMO. Been using the black theme in this commit of mine at even 4 AM in the night and it does not hurt the eye at all also the 10% color won't really be a drawback for AMOLED displays. That's my opinion

**Comment by naman14** [comment]
@CallMeAldy Hmm, okay, seems right. I will merge it then

**Comment by naman14** [comment]
@CallMeAldy  Shouldn't toolbar colors be different for different themes? I just pulled the changes to my machine, you have made the toolbar color same for all three themes

**Comment by prempalsingh** [comment]
I think changing the theme shouldn't affect the toolbar color. It would be
great though to have an option to customize the primary and accent color
irrespective of the theme. I'll try to implement that and send a PR.

**Comment by CallMeAldy** [comment]
@naman14 Being honest, it does not really matter having different toolbar colors for different theme styles. It's usually the same but again this comes under personal preference if you leave aside the material guidelines.

**Comment by naman14** [comment]
We seriously need a Theme engine now:pensive:

**Comment by jsjan** [comment]
@naman14 +1 for a theme engine. Would be nice to see, so other users can share them. Also a online repository with themes would be nice!

**Comment by srisurya95** [comment]
Thank you for mergeing ...It will be more beautiful now

**Pull request merged**
