### PR TITLE
Tablet UI

### PR DESCRIPTION
**Pull request by nv95**
I think, it looks great, aren't?

screenshot_2016-11-07-18-29-22
screenshot_2016-11-07-18-32-25

### CODE REVIEW

**Comment by fedor1113** [comment]
It looks great! Is it going to be implemented? Do not have much time to look into it, but it seems that it won't build - maybe you could correct it, so that @naman14 could accept it? It just seems like such a nice improvement - I have a phone, but still would like to be able to rotate my screen and see everything displayed correctly without overlapping.

**Comment by fedor1113** [comment]
Sorry, my bad - just misinterpreted what I've read, but it still displays "This branch has conflicts that must be resolved", so maybe you could resolve the conflicts locally, so that @naman14 could merge it with less trouble? I just really don't have time right now, but need this feature badly..

**Comment by naman14** [comment]
There are no problems with the conflicts, that I can rebase.
However, there were some issues with the layout and other things when I checked this out before the previous release. I will list all the issues by checking out the branch again that needs to be fixed.

**Comment by fedor1113** [comment]
OK, cool. @naman14, thank you for your fast reply!

**Pull request closed without merging**
