### PR TITLE
Added german (DE) translation

### PR DESCRIPTION
**Pull request by jan509**
I love the app, and because I am from Germany I added the german translation :relaxed:

### CODE REVIEW

**Comment by naman14** [comment]
Thanks for translating! Unfortunately many strings are still hardcoded inside the app. I will clean everything once and add them to strings and will let you know.

**Comment by jsjan** [comment]
@naman14 Ok, I leave this open and will work on that if you cleaned up!

**Comment by CallMeAldy** [comment]
@naman14 I can do the cleaning if you haven't started doing it yet.

**Comment by naman14** [comment]
@CallMeAldy yeah sure, I haven't started yet, that will be great!

**Comment by CallMeAldy** [comment]
@naman14 I'll get onto it in a bit then.

**Comment by solnj** [comment]
@CallMeAldy @naman14 Any updates on this? :)

**Comment by naman14** [comment]
I think @CallMeAldy is currently busy with M and mako. I will do it as soon as possible. 
Btw @CallMeAldy great work with mako till now :)

**Comment by Vic31** [comment]
Sorry to interrupt but I'm fresh here.So I downloaded the project and the playing list is empty. How to add songs in your app again?

**Comment by solnj** [comment]
@Vic31 Do you have any songs on your device? I have placed all my songs on my sdcard in a ``Music`` folder, create one and move them into this, should work!

**Comment by naman14** [comment]
@solnj Strings have been fixed, you can pull the changes and translate the rest of the strings

**Comment by solnj** [comment]
I rebase and the I translate the rest :)

**Comment by jan509** [comment]
@naman14 Did it!

**Comment by naman14** [comment]
@jan509 Great!

**Pull request merged**
